theme = [
    ('list-header', '', '', '', '', ''),
    ('list-header-column', 'black', 'light gray', '', 'light gray', 'g17'),
    ('list-header-column-separator', 'black', 'light gray', '', 'light gray', 'g17'),
    ('striped-table-row', 'white', 'dark gray', '', 'light gray', 'g12'),
    ('reveal focus', 'black', 'dark cyan', 'standout', 'black', 'dark blue'),
    ('message status', 'black', 'yellow', 'standout', 'black', 'yellow'),
    ('message error', 'white', 'dark red', 'standout', 'white', 'dark red'),
    ('status', 'dark magenta', 'black', '', 'dark magenta', 'black'),
    ('flash off', 'black', 'black', 'standout', 'black', 'black'),
    ('flash on', 'white', 'black', 'standout', 'white', 'black'),
    ('pop_up', 'white', 'black', '', 'white', 'black'),
    ('button action', 'white', 'light red', '', 'white', 'light red'),
    ('button cancel', 'black', 'light gray', '', 'black', 'light gray'),
]
